Repository RedHatInsights/sources-ui, pull requests merged in 2019-12, with the labels that each got.

#166 Add support for filtering by source_type
  src/api/entities.js
  src/pages/SourcesPage.js
  src/pages/SourcesPage/helpers.js
  src/redux/action-types-providers.js
  src/redux/actions/providers.js
  src/redux/reducers/providers.js
  src/test/api/helpers.spec.js
  src/test/components/SourcesSimpleView/SourcesSimpleView.spec.js
  src/test/pages/SourcePage/helpers.spec.js
  src/test/pages/SourcesPage.spec.js
  src/test/redux/actions.spec.js
  src/test/redux/reducer.spec.js
Labels: enhancement

#169 Fix passing arguments for loadEntities
  src/redux/actions/providers.js
  src/test/redux/actions.spec.js
Labels: bug

#171 Edit form ux feedback
  src/App.scss
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/parser/helpers.js
  src/components/editField/EditField.js
  src/test/components/sourceEditForm/parser/helpers.spec.js
Labels: enhancement

#165 Add availability status column
  src/App.scss
  src/api/entities.js
  src/components/SourcesSimpleView/formatters.js
  src/test/applicationTypesData.js
  src/test/components/SourcesSimpleView/formatters.spec.js
  src/views/sourcesViewDefinition.js
Labels: enhancement, wip

#172 Set pageNumber to 1 when filtering
  src/pages/SourcesPage.js
  src/redux/actions/providers.js
  src/redux/reducers/providers.js
  src/test/redux/actions.spec.js
  src/test/redux/reducer.spec.js
Labels: bug

#175 Update DDF and wizard
  package-lock.json
  package.json
Labels: dependencies

#174 Show errors only for unavailable apps
  src/api/entities.js
  src/components/SourcesSimpleView/formatters.js
  src/test/components/SourcesSimpleView/formatters.spec.js
Labels: bug

#177 Send to endpoint API when editing url
  src/api/doUpdateSource.js
  src/test/api/doUpdateSource.spec.js
Labels: bug

#176 Update frontend-components-sources to support Cost Mgmt OCP sources
  package-lock.json
  package.json
Labels: dependencies, unmergeable

#181 Allow editing Cluster Identifier for CM/Openshift
  src/components/SourceEditForm/parser/application.js
  src/components/SourceEditForm/parser/parseSourceToSchema.js
  src/test/components/sourceEditForm/parseSourceToSchema.spec.js
  src/test/components/sourceEditForm/parser/application.spec.js
  src/test/components/sourceEditForm/parser/parseSourceToSchema.spec.js
Labels: enhancement

#183 Update availability status
  src/App.scss
  src/components/SourcesSimpleView/formatters.js
  src/test/components/SourcesSimpleView/formatters.spec.js
Labels: enhancement

#184 Use logger only on dev
  src/App.js
  src/Utilities/store.js
  src/entry-dev.js
  src/entry.js
  src/test/app.spec.js
  src/test/utilities/store.spec.js
Labels: technical debt

#186 Set default sortBy and sortDirection
  src/redux/reducers/providers.js
Labels: enhancement

#190 Do not edit not-auth names in authentication edit form
  src/components/SourceEditForm/parser/authentication.js
  src/test/components/sourceEditForm/parser/authentication.spec.js
Labels: bug

#192 Sort SourceTypes in filter alphabetically
  src/pages/SourcesPage/helpers.js
  src/test/pages/SourcePage/helpers.spec.js
Labels: enhancement

#191 Fetch and update cost management values in edit
  src/api/doLoadSourceForEdit.js
  src/api/doUpdateSource.js
  src/api/entities.js
  src/api/getCmValues.js
  src/api/patchCmValues.js
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/helpers.js
  src/components/SourceEditForm/onSubmit.js
  src/test/api/doLoadSourceForEdit.spec.js
  src/test/api/doUpdateSource.spec.js
  src/test/components/sourceEditForm/SourceEditModal.spec.js
  src/test/components/sourceEditForm/helpers.spec.js
  src/test/components/sourceEditForm/onSubmit.spec.js
Labels: bug

#193 Npm update and npm audit
  package-lock.json
  package.json
Labels: technical debt

#194 Fix missing aria-label on Filter by name
  src/pages/SourcesPage.js
Labels: technical debt

#195 Update Wizard to contain Azure-CM
  package-lock.json
  package.json
Labels: dependencies

#196 Update submit handling in edit form
  package-lock.json
  package.json
  src/Utilities/SourcesFormRenderer.js
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/onSubmit.js
  src/redux/actions/providers.js
  src/test/components/sourceEditForm/SourceEditModal.spec.js
  src/test/components/sourceEditForm/onSubmit.spec.js
  src/test/redux/actions.spec.js
Labels: enhancement

#197 Fix column width in row loader
  src/components/SourcesSimpleView/loaders.js
  src/test/components/SourcesSimpleView/loaders.spec.js
  src/views/sourcesViewDefinition.js
Labels: enhancement

#182 Allow editing Credentials CM values
  src/api/doLoadSourceForEdit.js
  src/api/doUpdateSource.js
  src/components/SourceEditForm/parser/application.js
  src/test/api/doLoadSourceForEdit.spec.js
  src/test/api/doUpdateSource.spec.js
  src/test/components/sourceEditForm/parser/application.spec.js
Labels: enhancement

#202 Prevent default of event on submit in edit form
  src/components/SourceEditForm/HorizontalFormWrapper.js
  src/test/components/sourceEditForm/HorizontalFormWrapper.spec.js
Labels: bug
