Repository RedHatInsights/sources-ui, pull requests merged in 2020-12, with the labels that each got.

#488 Add rename source modal
  src/components/SourceDetail/SourceKebab.js
  src/components/SourceDetail/SourceRenameModal.js
  src/pages/Detail.js
  src/redux/sources/actionTypes.js
  src/redux/sources/actions.js
  src/redux/sources/reducer.js
  src/test/components/sourceDetail/SourceKebab.test.js
  src/test/components/sourceDetail/SourceRenameModal.test.js
  src/test/pages/Detail.test.js
  src/test/redux/sources/actions.test.js
  src/test/redux/sources/reducer.test.js
Labels: enhancement

#489 Update wizard to latest, detail followup
  package-lock.json
  package.json
  src/Routes.js
  src/components/SourceDetail/SourceSummaryCard.js
  src/test/components/sourceDetail/SourceSummaryCard.test.js
Labels: bug, dependencies

#490 Add availability check button to source detail
  src/api/checkSourceStatus.js
  src/components/SourceDetail/AvailabilityChecker.js
  src/components/SourceDetail/SourceSummaryCard.js
  src/test/components/sourceDetail/AvailabilityChecker.test.js
  src/test/components/sourceDetail/SourceSummaryCard.test.js
Labels: enhancement

#492 Update travis URL in README file
  README.md
Labels: technical debt

#491 Show errors/timeouts in error tabs
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/TimeoutedModal.js
  src/components/SourceEditForm/onSubmit.js
  src/components/SourceEditForm/parser/EditAlert.js
  src/components/SourceEditForm/parser/application.js
  src/components/SourceEditForm/parser/parseSourceToSchema.js
  src/components/SourceEditForm/reducer.js
  src/test/components/sourceEditForm/SourceEditModal.test.js
  src/test/components/sourceEditForm/onSubmit.test.js
  src/test/components/sourceEditForm/parser/EditAlert.test.js
  src/test/components/sourceEditForm/parser/application.test.js
  src/test/components/sourceEditForm/parser/parseSourceToSchema.test.js
  src/test/components/sourceEditForm/timetoutedModal.test.js
Labels: enhancement

#493 Remove button from empty source state for only-read
  src/components/SourcesEmptyState.js
  src/test/components/SourcesEmptyState.test.js
Labels: enhancement

#494 Split the table to Cloud sources and RedHat sources
  src/api/entities.js
  src/components/TabNavigation.js
  src/pages/Sources.js
  src/pages/Sources/helpers.js
  src/redux/sources/actionTypes.js
  src/redux/sources/actions.js
  src/redux/sources/reducer.js
  src/test/api/helpers.test.js
  src/test/components/TabNavigation.test.js
  src/test/pages/Sources.test.js
  src/test/pages/Sources/helpers.test.js
  src/test/redux/sources/actions.test.js
  src/test/utilities/urlQuery.test.js
  src/utilities/constants.js
  src/utilities/urlQuery.js
Labels: enhancement

#495 Update empty state table
  src/components/SourcesEmptyState.js
  src/components/SourcesTable/SourcesEmptyState.js
  src/components/SourcesTable/SourcesTable.js
  src/pages/Sources.js
  src/test/components/SourcesEmptyState.test.js
  src/test/components/sourcesTable/SourcesTable.test.js
  src/test/pages/Sources.test.js
Labels: enhancement

#496 Fix wording in Sources empty state
  src/components/SourcesTable/SourcesEmptyState.js
  src/test/components/SourcesEmptyState.test.js
  src/test/components/sourcesTable/SourcesEmptyState.test.js
Labels: bug

#497 Fix date formatter spanning
  src/views/formatters.js
Labels: bug

#498 Check only edited applications in edit form
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/helpers.js
  src/components/SourceEditForm/onSubmit.js
  src/test/components/sourceEditForm/SourceEditModal.test.js
  src/test/components/sourceEditForm/helpers.test.js
  src/test/components/sourceEditForm/onSubmit.test.js
Labels: bug

#499 Set initial warning messages in source edit
  src/api/entities.js
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/helpers.js
  src/components/SourceEditForm/onSubmit.js
  src/components/SourceEditForm/parser/parseSourceToSchema.js
  src/components/SourceEditForm/reducer.js
  src/test/components/sourceEditForm/SourceEditModal.test.js
  src/test/components/sourceEditForm/helpers.test.js
  src/test/components/sourceEditForm/onSubmit.test.js
  src/test/components/sourceEditForm/parser/parseSourceToSchema.test.js
Labels: enhancement

#500 Update sources wizard to limit source/app types
  package-lock.json
  package.json
  src/pages/Sources.js
  src/redux/sources/reducer.js
Labels: enhancement

#501 Change cloud sources icon
  src/components/TabNavigation.js
  src/test/components/TabNavigation.test.js
Labels: bug

#508 Update documentation with Cloud/Red Hat sources
  README.md
  doc/images/sources-main-add.jpg
  doc/images/sources-main-add.png
  doc/update-wizard.md
Labels: technical debt

#509 Update package.json
  package-lock.json
  package.json
Labels: dependencies, technical debt

#510 Change applications column to use label group
  src/api/entities.js
  src/test/views/formatters.test.js
  src/views/formatters.js
  src/views/sourcesViewDefinition.js
Labels: enhancement

#511 Fix missing status in edit when no error is set
  src/api/entities.js
  src/components/SourceEditForm/helpers.js
  src/test/components/sourceEditForm/SourceEditModal.test.js
  src/test/components/sourceEditForm/helpers.test.js
Labels: bug

#512 Add labels for apps in detail
  src/components/SourceDetail/ApplicationStatusLabel.js
  src/components/SourceDetail/ApplicationsCard.js
  src/components/SourcesTable/SourcesTable.js
  src/test/components/sourceDetail/ApplicationStatusLabel.test.js
  src/test/components/sourceDetail/ApplicationsCard.test.js
  src/test/components/sourcesTable/SourcesTable.test.js
  src/views/formatters.js
Labels: enhancement

#513 Change wording on See more label in applications
  src/test/views/formatters.test.js
  src/views/formatters.js
Labels: bug

#518 Update package.json and lock
  package-lock.json
  package.json
Labels: dependencies

#519 Remove None from Red Hat applications
  package-lock.json
  package.json
Labels: dependencies

#520 Update cost steps in add source wizard
  package-lock.json
  package.json
Labels: dependencies
