Repository RedHatInsights/sources-ui, pull requests merged in 2020-06, with the labels that each got.

#357 Refactor to remove update errors, refactor editForm to use context
  src/components/EditField/EditField.js
  src/components/EditField/EditFieldWrapper.js
  src/components/RedirectNoId/RedirectNoId.js
  src/components/RedirectNotAdmin/RedirectNotAdmin.js
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/parser/application.js
  src/components/SourceEditForm/parser/authentication.js
  src/components/SourceEditForm/parser/endpoint.js
  src/components/SourceEditForm/parser/genericInfo.js
  src/components/SourceEditForm/parser/helpers.js
  src/components/SourceEditForm/parser/parseSourceToSchema.js
  src/components/SourceEditForm/reducer.js
  src/test/components/editField/editField.test.js
  src/test/components/editField/editFieldWrapper.test.js
  src/test/components/sourceEditForm/parser/application.test.js
  src/test/components/sourceEditForm/parser/authentication.test.js
  src/test/components/sourceEditForm/parser/genericInfo.test.js
  src/test/components/sourceEditForm/parser/helpers.test.js
  src/test/components/sourceEditForm/parser/parseSourceToSchema.test.js
  src/utilities/SourcesFormRenderer.js
Labels: bug, technical debt

#358 Update FC to V2
  config/base.webpack.plugins.js
  package-lock.json
  package.json
  src/App.js
  src/components/AddApplication/AddApplicationSchema.js
  src/components/SourceEditForm/parser/application.js
  src/components/SourceEditForm/parser/authentication.js
  src/components/SourceEditForm/parser/endpoint.js
  src/components/SourceEditForm/parser/genericInfo.js
  src/components/SourcesTable/formatters.js
  src/components/SourcesTable/loaders.js
  src/pages/Sources.js
  src/redux/sources/actions.js
  src/test/app.test.js
  src/test/components/sourcesTable/formatters.test.js
  src/test/components/sourcesTable/loaders.test.js
  src/test/pages/Sources.test.js
  src/utilities.scss
  src/utilities/store.js
Labels: dependencies

#359 Unify loading/errored steps
  src/components/AddApplication/AddApplication.js
  src/components/AddApplication/steps/ErroredStep.js
  src/components/AddApplication/steps/LoadingStep.js
  src/test/components/addApplication/AddApplication.test.js
  src/test/components/addApplication/steps/ErroredStep.test.js
  src/test/components/addApplication/steps/LoadingStep.test.js
Labels: technical debt

#362 Update wizard to V2
  package-lock.json
  package.json
  src/api/doAttachApp.js
  src/components/AddApplication/AddApplication.js
  src/components/AddApplication/AddApplicationSchema.js
  src/components/SourceEditForm/parser/RemoveAuth.js
  src/components/SourceEditForm/parser/application.js
  src/components/SourceEditForm/parser/authentication.js
  src/components/SourceEditForm/parser/endpoint.js
  src/components/SourceEditForm/parser/genericInfo.js
  src/pages/Sources.js
  src/test/api/doAttachApp.test.js
  src/test/components/addApplication/AddApplication.test.js
  src/test/components/sourceEditForm/SourceEditModal.test.js
  src/test/components/sourceEditForm/parser/application.test.js
  src/test/components/sourceEditForm/parser/authentication.test.js
  src/test/components/sourceEditForm/parser/endpoint.test.js
  src/test/components/sourceEditForm/parser/genericInfo.test.js
  src/test/pages/Sources.test.js
  src/test/pages/SourcesAddRoute.test.js
  src/utilities/SourcesFormRenderer.js
Labels: dependencies, technical debt

#363 Update FC packages to minified versions
  package-lock.json
  package.json
Labels: dependencies

#365 Small UX fixes
  src/App.scss
  src/components/AddApplication/AddApplicationSchema.js
  src/components/SourceEditForm/SourceEditModal.js
  src/components/SourceEditForm/parser/RemoveAuth.js
  src/components/SourcesTable/formatters.js
  src/test/components/addApplication/addApplicationSchema.test.js
  src/test/components/sourceEditForm/parser/removeAuth.test.js
  src/test/components/sourcesTable/SourcesTable.test.js
  src/test/components/sourcesTable/formatters.test.js
  src/views/sourcesViewDefinition.js
Labels: enhancement

#368 Update everything
  .stylelint.json
  package-lock.json
  package.json
Labels: dependencies, technical debt

#370 Do clean install of package-lock.json
  package-lock.json
Labels: dependencies, technical debt

#373 Adjust custom_release to match new strategy
  .travis/custom_release.sh
Labels: enhancement

#374 Fix elliptic vulnerability issue
  package-lock.json
  package.json
Labels: bug, dependencies
