Repository RedHatInsights/sources-ui, pull requests merged in 2021-04, with the labels that each got.

#641 Fix frontend assets link
  README.md
Labels: technical debt

#643 Update cloud info cards text and links
  src/components/CloudTiles/CloudCards.js
Labels: enhancement

#642 Fix bulkCreate to link endpoint via hostname
  src/api/createSource.js
  src/test/api/createSource.test.js
Labels: bug

#648 Add Learn more link to Google project step
  package-lock.json
  src/components/addSourceWizard/hardcodedComponents/gcp/costManagement.js
  src/test/addSourceWizard/addSourceWizard/hardCodedComponents/google_cost.test.js
Labels: dependencies, enhancement

#650 Add in progress status
  src/test/views/formatters.test.js
  src/views/formatters.js
Labels: enhancement, superkey

#651 Negate vendor attribute to get cloud sources
  src/api/entities.js
  src/test/api/entities.test.js
  src/test/api/helpers.test.js
  src/utilities/constants.js
Labels: enhancement

#649 Add support for azure + subwatch
  src/components/AddApplication/AddApplicationSchema.js
  src/components/AddApplication/schema/generateFirstAuthStep.js
  src/components/SourceDetail/ResourcesEmptyState.js
  src/components/SourceDetail/ResourcesTable.js
  src/components/SourceEditForm/parser/application.js
  src/components/addSourceWizard/descriptions/SubWatchDescription.js
  src/components/addSourceWizard/emptyAuthType.js
  src/components/addSourceWizard/hardcodedComponents/azure/subscriptionWatch.js
  src/components/addSourceWizard/hardcodedSchemas.js
  src/components/addSourceWizard/schemaBuilder.js
  src/test/__mocks__/applicationTypesData.js
  src/test/__mocks__/sourceTypesData.js
  src/test/addSourceWizard/addSourceWizard/descriptions/subWatchDescription.test.js
  src/test/addSourceWizard/addSourceWizard/hardCodedComponents/azure_subwatch.test.js
  src/test/addSourceWizard/addSourceWizard/schemaBuilder.test.js
  src/test/addSourceWizard/helpers/applicationTypes.js
  src/test/components/addApplication/addApplicationSchema.test.js
  src/test/components/formComponents/sourceWizardSummary.test.js
  src/test/components/sourceDetail/ResourcesTable.test.js
  src/test/components/sourceEditForm/parser/application.test.js
Labels: enhancement

#652 Ignore empty auth type in api calls
  src/api/createSource.js
  src/api/doAttachApp.js
  src/test/api/createSource.test.js
  src/test/api/doAttachApp.test.js
Labels: bug

#654 Maintenance and some styling issues
  package-lock.json
  package.json
  src/App.scss
  src/components/SourceDetail/ApplicationsCard.js
  src/pages/Sources.js
  src/test/pages/Sources.test.js
Labels: bug, dependencies, technical debt

#655 Add warning alert for Azure/Rhel combo
  src/components/FormComponents/SourceWizardSummary.js
  src/test/components/formComponents/sourceWizardSummary.test.js
Labels: enhancement

#656 Fix cost popover checkbox variant
  src/App.scss
  src/components/FormComponents/CheckboxWithIcon.js
  src/components/addSourceWizard/hardcodedComponents/aws/arn.js
  src/components/addSourceWizard/hardcodedSchemas.js
  src/test/addSourceWizard/addSourceWizard/hardCodedComponents/arn.test.js
  src/test/components/formComponents/checkboxWithIcon.test.js
  src/utilities/SourcesFormRenderer.js
Labels: bug

#658 Use dropdown item on mobile screen instead of button
  config/setupTests.js
  package-lock.json
  package.json
  src/hooks/useScreen.js
  src/pages/Sources.js
  src/test/hooks/useScreen.test.js
  src/test/pages/Sources.test.js
Labels: dependencies, enhancement

#659 Update Cost Management doc links
  src/components/addSourceWizard/hardcodedComponents/aws/arn.js
  src/components/addSourceWizard/hardcodedComponents/azure/costManagement.js
  src/components/addSourceWizard/hardcodedComponents/gcp/costManagement.js
  src/components/addSourceWizard/hardcodedComponents/openshift/costManagement.js
Labels: enhancement

#660 Remove blank line
  src/components/addSourceWizard/hardcodedComponents/aws/arn.js
Labels: technical debt

#663 Use frontend components error state
  package-lock.json
  package.json
  src/components/SourcesErrorState.js
  src/pages/Sources.js
  src/test/components/SourcesErrorState.test.js
  src/test/pages/Sources.test.js
Labels: technical debt
